//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Band_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductDetail
    {
        public int ProductDetailId { get; set; }
        public int ProductId { get; set; }
        public int ProductInStore { get; set; }
        public decimal ProductUnitPrice { get; set; }
        public string ProductImage { get; set; }
        public System.DateTime LastEditDate { get; set; }
    
        public virtual tProduct tProduct { get; set; }
    }
}
