//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Band_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReply
    {
        public int ReplyId { get; set; }
        public int PostId { get; set; }
        public string ReplyContent { get; set; }
        public int ReplyLikeCount { get; set; }
        public int ReplyDislikeCount { get; set; }
        public System.DateTime LastEditDate { get; set; }
    }
}
