//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Band_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUser()
        {
            this.tOrder = new HashSet<tOrder>();
            this.tTicketPurchase = new HashSet<tTicketPurchase>();
        }
    
        public int UserId { get; set; }
        public string UserAccount { get; set; }
        public byte[] UserPassword { get; set; }
        public string UserEmail { get; set; }
        public string UserSexual { get; set; }
        public System.DateTime UserBirthday { get; set; }
        public string UserAddress { get; set; }
        public string UserPhone { get; set; }
        public string UserCountry { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public byte[] UserSalt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder> tOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTicketPurchase> tTicketPurchase { get; set; }
    }
}
